2017-07-15 10:13:48,729 - root - [ERROR]: True
None
2017-07-15 10:13:48,732 - root - [ERROR]: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "click_log_processor.py", line 116, in run
    handle_msg(msg)
  File "click_log_processor.py", line 91, in handle_msg
    logging.error('class' not in news, exc_info = True)
TypeError: argument of type 'NoneType' is not iterable
2017-07-15 10:13:53,779 - root - [ERROR]: True
Traceback (most recent call last):
  File "click_log_processor.py", line 116, in run
    handle_msg(msg)
  File "click_log_processor.py", line 91, in handle_msg
    logging.error('class' not in news, exc_info = True)
TypeError: argument of type 'NoneType' is not iterable
2017-07-15 10:13:53,782 - root - [ERROR]: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "click_log_processor.py", line 116, in run
    handle_msg(msg)
  File "click_log_processor.py", line 91, in handle_msg
    logging.error('class' not in news, exc_info = True)
TypeError: argument of type 'NoneType' is not iterable
2017-07-15 10:13:58,843 - root - [ERROR]: False
Traceback (most recent call last):
  File "click_log_processor.py", line 116, in run
    handle_msg(msg)
  File "click_log_processor.py", line 91, in handle_msg
    logging.error('class' not in news, exc_info = True)
TypeError: argument of type 'NoneType' is not iterable
2017-07-15 10:13:58,852 - root - [ERROR]: True
Traceback (most recent call last):
  File "click_log_processor.py", line 116, in run
    handle_msg(msg)
  File "click_log_processor.py", line 91, in handle_msg
    logging.error('class' not in news, exc_info = True)
TypeError: argument of type 'NoneType' is not iterable
2017-07-15 10:13:58,855 - root - [ERROR]: 'class'
Traceback (most recent call last):
  File "click_log_processor.py", line 116, in run
    handle_msg(msg)
  File "click_log_processor.py", line 92, in handle_msg
    logging.error(news['class'] not in NEWS_CLASSES, exc_info = True)
KeyError: 'class'
2017-07-15 12:40:51,281 - root - [ERROR]: JsonRpcError(-32603): global name 'NEWS_CLASSES' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 95, in getNewsSummariesForUser
    or news['class'] not in NEWS_CLASSES):
NameError: global name 'NEWS_CLASSES' is not defined

2017-07-15 13:07:57,876 - root - [ERROR]: JsonRpcError(-32603): global name 'NEWS_CLASSES' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 95, in getNewsSummariesForUser
    or news['class'] not in NEWS_CLASSES):
NameError: global name 'NEWS_CLASSES' is not defined

2017-07-15 13:10:05,505 - root - [ERROR]: JsonRpcError(-32603): global name 'NEWS_CLASSES' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 95, in getNewsSummariesForUser
    or news['class'] not in NEWS_CLASSES):
NameError: global name 'NEWS_CLASSES' is not defined

2017-07-15 13:14:56,433 - root - [ERROR]: JsonRpcError(-32603): global name 'NEWS_CLASSES' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    return operations.getNewsSummariesForUser(user_id, page_num)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 95, in getNewsSummariesForUser
    or 'class' not in news
NameError: global name 'NEWS_CLASSES' is not defined

2017-07-15 13:16:33,551 - root - [ERROR]: False
None
2017-07-15 13:16:33,553 - root - [ERROR]: False
None
2017-07-15 13:16:33,554 - root - [ERROR]: True
None
2017-07-15 13:16:33,555 - root - [ERROR]: False
None
2017-07-15 13:16:33,556 - root - [ERROR]: False
None
2017-07-15 13:16:33,558 - root - [ERROR]: True
None
2017-07-15 13:16:33,559 - root - [ERROR]: False
None
2017-07-15 13:16:33,562 - root - [ERROR]: False
None
2017-07-15 13:16:33,563 - root - [ERROR]: True
None
2017-07-15 13:16:33,568 - root - [ERROR]: False
None
2017-07-15 13:16:33,568 - root - [ERROR]: False
None
2017-07-15 13:16:33,569 - root - [ERROR]: True
None
2017-07-15 13:17:18,066 - root - [ERROR]: False
None
2017-07-15 13:17:18,069 - root - [ERROR]: False
None
2017-07-15 13:17:18,075 - root - [ERROR]: True
None
2017-07-15 13:17:18,077 - root - [ERROR]: False
None
2017-07-15 13:17:18,077 - root - [ERROR]: False
None
2017-07-15 13:17:18,078 - root - [ERROR]: True
None
2017-07-15 13:17:18,079 - root - [ERROR]: False
None
2017-07-15 13:17:18,080 - root - [ERROR]: False
None
2017-07-15 13:17:18,081 - root - [ERROR]: True
None
2017-07-15 13:24:59,219 - root - [ERROR]: False
None
2017-07-15 13:24:59,223 - root - [ERROR]: False
None
2017-07-15 13:24:59,227 - root - [ERROR]: True
None
2017-07-15 13:24:59,229 - root - [ERROR]: False
None
2017-07-15 13:24:59,234 - root - [ERROR]: False
None
2017-07-15 13:24:59,243 - root - [ERROR]: True
None
2017-07-15 13:24:59,253 - root - [ERROR]: False
None
2017-07-15 13:24:59,254 - root - [ERROR]: False
None
2017-07-15 13:24:59,256 - root - [ERROR]: True
None
2017-07-15 13:24:59,259 - root - [ERROR]: False
None
2017-07-15 13:24:59,271 - root - [ERROR]: False
None
2017-07-15 13:24:59,274 - root - [ERROR]: True
None
2017-07-15 13:26:51,315 - root - [ERROR]: False
None
2017-07-15 13:26:51,317 - root - [ERROR]: False
None
2017-07-15 13:26:51,318 - root - [ERROR]: True
None
2017-07-15 13:26:51,319 - root - [ERROR]: False
None
2017-07-15 13:26:51,320 - root - [ERROR]: False
None
2017-07-15 13:26:51,322 - root - [ERROR]: True
None
2017-07-15 13:26:51,327 - root - [ERROR]: False
None
2017-07-15 13:26:51,332 - root - [ERROR]: False
None
2017-07-15 13:26:51,333 - root - [ERROR]: True
None
2017-07-15 13:26:51,340 - root - [ERROR]: False
None
2017-07-15 13:26:51,341 - root - [ERROR]: False
None
2017-07-15 13:26:51,342 - root - [ERROR]: True
None
2017-07-15 13:34:12,811 - root - [ERROR]: False
None
2017-07-15 13:34:12,813 - root - [ERROR]: False
None
2017-07-15 13:34:12,815 - root - [ERROR]: True
None
2017-07-15 13:34:12,816 - root - [ERROR]: False
None
2017-07-15 13:34:12,816 - root - [ERROR]: False
None
2017-07-15 13:34:12,817 - root - [ERROR]: True
None
2017-07-15 13:34:12,823 - root - [ERROR]: False
None
2017-07-15 13:34:12,828 - root - [ERROR]: False
None
2017-07-15 13:34:12,828 - root - [ERROR]: True
None
2017-07-15 13:34:12,829 - root - [ERROR]: False
None
2017-07-15 13:34:12,830 - root - [ERROR]: False
None
2017-07-15 13:34:12,831 - root - [ERROR]: True
None
2017-07-15 13:42:32,663 - root - [ERROR]: False
None
2017-07-15 13:42:32,665 - root - [ERROR]: False
None
2017-07-15 13:42:32,666 - root - [ERROR]: True
None
2017-07-15 13:42:32,667 - root - [ERROR]: False
None
2017-07-15 13:42:32,668 - root - [ERROR]: False
None
2017-07-15 13:42:32,669 - root - [ERROR]: True
None
2017-07-15 13:42:32,676 - root - [ERROR]: False
None
2017-07-15 13:42:32,679 - root - [ERROR]: False
None
2017-07-15 13:42:32,686 - root - [ERROR]: True
None
2017-07-15 13:42:32,696 - root - [ERROR]: False
None
2017-07-15 13:42:32,700 - root - [ERROR]: False
None
2017-07-15 13:42:32,701 - root - [ERROR]: True
None
2017-07-15 13:46:27,010 - root - [ERROR]: False
None
2017-07-15 13:46:27,013 - root - [ERROR]: False
None
2017-07-15 13:46:27,037 - root - [ERROR]: True
None
2017-07-15 13:46:27,040 - root - [ERROR]: False
None
2017-07-15 13:46:27,044 - root - [ERROR]: False
None
2017-07-15 13:46:27,045 - root - [ERROR]: True
None
2017-07-15 13:46:27,047 - root - [ERROR]: False
None
2017-07-15 13:46:27,049 - root - [ERROR]: False
None
2017-07-15 13:46:27,052 - root - [ERROR]: True
None
2017-07-15 13:46:27,053 - root - [ERROR]: False
None
2017-07-15 13:46:27,055 - root - [ERROR]: False
None
2017-07-15 13:46:27,056 - root - [ERROR]: True
None
2017-07-15 13:46:57,821 - root - [ERROR]: False
None
2017-07-15 13:46:57,829 - root - [ERROR]: False
None
2017-07-15 13:46:57,845 - root - [ERROR]: True
None
2017-07-15 13:46:57,848 - root - [ERROR]: False
None
2017-07-15 13:46:57,850 - root - [ERROR]: False
None
2017-07-15 13:46:57,850 - root - [ERROR]: True
None
2017-07-15 13:46:57,852 - root - [ERROR]: False
None
2017-07-15 13:46:57,853 - root - [ERROR]: False
None
2017-07-15 13:46:57,854 - root - [ERROR]: True
None
2017-07-15 13:46:57,856 - root - [ERROR]: False
None
2017-07-15 13:46:57,866 - root - [ERROR]: False
None
2017-07-15 13:46:57,872 - root - [ERROR]: True
None
2017-07-15 13:53:07,552 - root - [ERROR]: False
None
2017-07-15 13:53:07,554 - root - [ERROR]: False
None
2017-07-15 13:53:07,556 - root - [ERROR]: True
None
2017-07-15 13:53:07,560 - root - [ERROR]: False
None
2017-07-15 13:53:07,561 - root - [ERROR]: False
None
2017-07-15 13:53:07,562 - root - [ERROR]: True
None
2017-07-15 13:53:07,564 - root - [ERROR]: False
None
2017-07-15 13:53:07,567 - root - [ERROR]: False
None
2017-07-15 13:53:07,570 - root - [ERROR]: True
None
2017-07-15 13:53:07,582 - root - [ERROR]: False
None
2017-07-15 13:53:07,590 - root - [ERROR]: False
None
2017-07-15 13:53:07,592 - root - [ERROR]: True
None
2017-07-16 12:51:24,175 - pika.adapters.base_connection - [ERROR]: Fatal Socket Error: error(32, 'Broken pipe')
2017-07-16 12:51:24,183 - root - [ERROR]: JsonRpcError(-32603): Internal JSON-RPC error. -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 34, in logNewsClickForUser
    return operations.logNewsClickForUser(user_id, news_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 126, in logNewsClickForUser
    cloudAMQP_client.sendMessage(message)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/../common/cloudAMQP_client.py", line 16, in sendMessage
    self.channel.basic_publish(exchange='', routing_key=self.queue_name, body=json.dumps(message))
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
    mandatory, immediate)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 2065, in publish
    self._flush_output()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

2017-07-16 12:55:26,739 - root - [ERROR]: JsonRpcError(-32603): Cannot encode object: <pymongo.cursor.Cursor object at 0x7f5bd2b46b90> -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 29, in getNewsHistoryForUser
    return operations.getNewsHistoryForUser(user_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 118, in getNewsHistoryForUser
    return json.loads(dumps(history_news))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 274, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in _json_convert
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in <genexpr>
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 124, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 291, in get_message
    spec, self.fields, self.codec_options)
InvalidDocument: Cannot encode object: <pymongo.cursor.Cursor object at 0x7f5bd2b46b90>

2017-07-16 12:59:26,967 - root - [ERROR]: JsonRpcError(-32603): Cannot encode object: <pymongo.cursor.Cursor object at 0x7f5bd1c41ed0> -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 29, in getNewsHistoryForUser
    def getNewsHistoryForUser(self, user_id):
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 118, in getNewsHistoryForUser
    return json.loads(dumps(history_news))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 274, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in _json_convert
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in <genexpr>
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 124, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 291, in get_message
    spec, self.fields, self.codec_options)
InvalidDocument: Cannot encode object: <pymongo.cursor.Cursor object at 0x7f5bd1c41ed0>

2017-07-16 13:01:14,084 - root - [ERROR]: JsonRpcError(-32603): Cannot encode object: <pymongo.cursor.Cursor object at 0x7ff5a4ca5450> -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 31, in getNewsHistoryForUser
    return operations.getNewsHistoryForUser(user_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 118, in getNewsHistoryForUser
    return json.loads(dumps(history_news))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 274, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in _json_convert
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in <genexpr>
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 124, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 291, in get_message
    spec, self.fields, self.codec_options)
InvalidDocument: Cannot encode object: <pymongo.cursor.Cursor object at 0x7ff5a4ca5450>

2017-07-16 13:13:21,243 - root - [ERROR]: JsonRpcError(-32602): Invalid method parameter(s). -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
TypeError: add() takes exactly 3 arguments (1 given)

2017-07-16 13:15:22,756 - root - [ERROR]: JsonRpcError(-32602): Invalid method parameter(s). -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
TypeError: add() takes exactly 3 arguments (1 given)

2017-07-16 13:19:36,266 - root - [ERROR]: JsonRpcError(-32603): Cannot encode object: <pymongo.cursor.Cursor object at 0x7f1250899610> -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 31, in getNewsHistoryForUser
    return operations.getNewsHistoryForUser(user_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 118, in getNewsHistoryForUser
    return json.loads(dumps(history_news))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 274, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in _json_convert
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/bson/json_util.py", line 307, in <genexpr>
    return list((_json_convert(v, json_options) for v in obj))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 124, in send_message_with_response
    set_slave_okay, sock_info.is_mongos, use_find_cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 291, in get_message
    spec, self.fields, self.codec_options)
InvalidDocument: Cannot encode object: <pymongo.cursor.Cursor object at 0x7f1250899610>

2017-07-16 13:53:14,677 - root - [ERROR]: JsonRpcError(-32603): global name 'itemgetter' is not defined -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 36, in getNewsHistoryForUser
    return operations.getNewsHistoryForUser(user_id)
  File "/home/thu/BitTigerCS503/bittigercs503-1702/capstone/backend_server/operations.py", line 113, in getNewsHistoryForUser
    click_log = map(itemgetter('newsId'),list(db[CLICK_LOG_TABLE_NAME].find({'userId': user_id}, {'newsId':1})))
NameError: global name 'itemgetter' is not defined

